### ISSUE TITLE
Warning: Command failed: /bin/sh -c vendor/phpunit/phpunit/phpunit tests/  Use --force to continue.

### ISSUE THREAD

**Issue by karneaud** [tailored-tunes/grunt-phpunit-runner#3]
I have installed in my project
- grunt-php
- grunt-phpunit-runner
## \- local project installed phpunit

I have the following in my Gruntfile

```
'phpunit-runner': {
    all: {
      options: {
        phpunit: 'vendor/phpunit/phpunit/phpunit',
        verbose: true
      },
      files: {
        testFiles: 'tests/'
      }
      }
    },
```

when I execute a grunt task I get the following error message

> Running "server" task
> 
> Running "php:dist" (php) task
> PHP 5.5.30 Development Server started at Sun Feb 28 23:25:15 2016
> Listening on http://127.0.0.1:9000
> Document root is /public
> Press Ctrl-C to quit.
> [Sun Feb 28 23:25:15 2016] 127.0.0.1:55627 [200]: /
> 
> Running "phpunit-runner:all" (phpunit-runner) task
> 
> Running "shell:phpunit-runner-0" (shell) task
> 
> > > PHPUnit 4.8.23 by Sebastian Bergmann and contributors.
> > > Warning:   The Xdebug extension is not loaded
> > >        No code coverage will be generated.
> > > 
> > > F
> > > 
> > > Time: 49 ms, Memory: 4.50Mb
> > > 
> > > There was 1 failure:
> > > 
> > > 1) Warning
> > > No tests found in class "ReferrerTest".
> > > 
> > > FAILURES!
> > > Tests: 1, Assertions: 0, Failures: 1.
> > > Warning: Command failed: /bin/sh -c vendor/phpunit/phpunit/phpunit tests/
> > >  Use --force to continue.
> 
> Aborted due to warnings.

Not sure what i mean. Would you have an idea of what I'm missing?

**Comment by kathiedart** [comment]
Looks like grunt is working correctly, what do you have in ReferrerTest? If just class ReferrerTest extends PHPUnit_xxxxx { } then this is expected behaviour.

**Comment by karneaud** [comment]
I see. Thanks
